stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest
  
maven-build: 
  stage: mavenbuild
  tags:
    - backend_tag1
  script:
    - cd Backend
    - cd nick_code
    - cd eclipse/Database
    - mvn package -B

maven-test:
  stage: maventest
  tags:
    - backend_tag1
  script:
    - cd Backend
    - cd nick_code
    - cd eclipse/Database
    - mvn test
  artifacts:
    paths:
      - Spring/target/*.jar

autoDeploy:
  stage: autodeploy
  tags:
    - backend_tag1
  script: 
    - cd Backend
    - cd nick_code
    - cd eclipse/Database
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl daemon-reload
    - sudo systemctl start system-web-demo
    - sudo systemctl stop system-web-demo
    
android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
    - android_tag1
  script:
    - cd Frontend
    - ./gradelew assemble
  artifacts:
    paths:
    - Frontend/app/build/outputs/
    
unitTests:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
    - android_tag1
  script:
    - cd Frontend
    - ./gradlew test

