stages: 
	- mavenbuild
	- maventest
	- autodeploy

maven-build: 
	stage: mavenbuild
	script:
		- cd Spring
	 	- mvn package -B

maven-test:
	stage: maventest
	script:
		- cd Sring
		- mvn test
	artifacts:
	paths:
		- Spring/target/*.jar

autoDeploy:
	stage: autodeploy 
	script: 
		- cd Spring 
		- mvn package -B

